name: Terraform CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      destroy:
        description: "Run terraform destroy (set to 'true' to trigger destroy job)"
        required: false
        default: "false"

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    env:
      TF_LOG: INFO
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Run Checkov for Security Scanning
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: ./Terra
        output_format: sarif # Ensure SARIF format is generated for upload
      continue-on-error: true  # This allows the workflow to continue even if this step fails


    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: results.sarif

    - name: Terraform Init
      run: terraform init
      working-directory: ./Terra

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./Terra

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Terra

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./Terra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve tfplan
      working-directory: ./Terra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Terraform Output
      run: terraform output
      working-directory: ./Terra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-destroy:
    runs-on: ubuntu-latest
    if: github.event.inputs.destroy == 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8

    - name: Terraform Init
      run: terraform init
      working-directory: ./Terra

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ./Terra
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
