name: Terraform CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      destroy:
        description: "Run terraform destroy (set to 'true' to trigger destroy job)"
        required: false
        default: "false"

jobs:
  terraform:
    if: github.event.inputs.destroy != 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write  

    env:
      TF_LOG: INFO
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TERRAFORM_DIRECTORY: ./Terra

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 

    - name: Configure AWS Credentials for GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4  
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
        audience: sts.amazonaws.com

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3  
      with:
        terraform_version: 1.9.8

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.TERRAFORM_DIRECTORY }}

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ${{ env.TERRAFORM_DIRECTORY }}

    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve tfplan
      working-directory: ${{ env.TERRAFORM_DIRECTORY }}

  terraform-destroy:
    if: github.event.inputs.destroy == 'true'
    runs-on: ubuntu-latest
    permissions:
      id-token: write 

    env:
      TF_LOG: INFO
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TERRAFORM_DIRECTORY: ./Terra

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  

    - name: Configure AWS Credentials for GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4  
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.AWS_REGION }}
        audience: sts.amazonaws.com

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3  
      with:
        terraform_version: 1.9.8

    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.TERRAFORM_DIRECTORY }}

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: ${{ env.TERRAFORM_DIRECTORY }}
